"""added contact model

Revision ID: 207ed650a7ea
Revises: 747eb789311f
Create Date: 2024-07-25 22:46:29.254815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207ed650a7ea'
down_revision = '747eb789311f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contacts_user_contact_users', type_='foreignkey')
        batch_op.drop_column('user_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_contact', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_contacts_user_contact_users', 'users', ['user_contact'], ['id'])

    # ### end Alembic commands ###
