"""added contact model

Revision ID: 747eb789311f
Revises: 0378f7c36de8
Create Date: 2024-07-25 22:33:10.089703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747eb789311f'
down_revision = '0378f7c36de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('user_contact', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_contact'], ['users.id'], name=op.f('fk_contacts_user_contact_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
